#!/usr/bin/env python3

#
# get-configuration/20read - Asset Manager MSP
#
# Rilegge SOLO i parametri non sensibili salvati da configure-module -
# password/chiavi di cifratura NON vengono mai restituite qui, restano
# leggibili solo dentro bootstrap_config.json sul disco del modulo.

import json
import sys
import os

config = {
    "fqdn": os.environ.get("FQDN", ""),
    "lets_encrypt": os.environ.get("LETS_ENCRYPT", "true") == "true",
    "db_host": os.environ.get("DB_HOST", ""),
    "db_port": int(os.environ.get("DB_PORT", "3306")),
    "db_name": os.environ.get("DB_NAME", ""),
    "db_user": os.environ.get("DB_USER", ""),
}

json.dump(config, fp=sys.stdout)
